### ISSUE TITLE
Calling functions in a specification

### ISSUE THREAD

**Issue by Coda-Coda** [completium/archetype-lang#200]
It would be nice to be able to call functions from within a specification. For example, the following code gives the error `No matches for function test(int)` on running `archetype -t whyml ...` but it would be preferable if it was possible to verify properties of functions.

If there is a way already to make this kind of thing work, please let me know :)

```
archetype trivial_test

entry exec () {
  effect {
    ()
  }
}

function test(x : int) : bool {
   if x < 10 then (
      return true
    ) else (
      return false
    )
}

specification {
  s1 : forall x : int, test(x) = true <-> x < 10
}
```

**Comment by rognierbenoit** [comment]
Hi Coda,

The issue is that functions may fail when accessing contract storage by key, which makes them unsuitable for specification.

You may however declare postconditions for functions, as for entries:

```
archetype trivial_test

function test(x : int) : bool {
   specification {
      p1 : result <-> x < 10; 
   }
   effect {  
      return (x < 10) 
   }
}

entry exec () {
  ()
}
```

However there could be indeed a notion of non-failing function to be used in contract specification. 
Please let me know if this is something you require.

**Comment by Coda-Coda** [comment]
Hi,

Thanks for the helpful and quick reply, your solution does indeed work for what I had in mind (and I had just worked it out for myself actually). I understand that the possibility of it failing would cause issues. I don't currently require more than what I now see is possible, though perhaps for completely pure functions (that do not even read contract storage) it could be useful to be able to use them in a specification and/or be able to specify additional properties about them in Why3. I was wondering whether using `function` instead of `let` in Why3 for these cases would be helpful, but I think that would interfere with what is currently possible with post-conditions.

In any case, I'm really impressed by Archetype so far and look forward to trying it out more. Thanks :)
