### ISSUE TITLE
Lack of Docs for Options Type

### ISSUE THREAD

**Issue by evronm** [completium/archetype-lang#327]
OK, so I'm using the following structure to store multiple token ledgers:  

```
variable tokens : map<string, iterable_big_map<address, nat >> = []
```
I'd much rather use assets for this, but partitions can't contain other partitions (any plans on changing that?).  The problem comes when I try to change the value of the internal iterable_big_map.  The [] returns an Options object, and there doesn't seem to be any documentation for how to update such objects.  

I've tried a few things, all of which led to errors.  Right now, I'm accessing the token balance with the following function:

```
function get_token_balance (sym : string, acct : address) : nat{
  return match tokens[sym] with
    | some(s) -> match s[acct] with
      | some(v) -> v 
      | none -> 0
    end
    | none -> 0
  end
}
```

(BTW, is there an easier way to do this???) but all my attempts at actually changing the value have come to naught.

Can someone please enlighten me?  

Also, is there a more appropriate place to ask questions like this?  I tried the slack link, but it didn't work for me for some reason.

Thanks in advance.

**Comment by rognierbenoit** [comment]
Hi Mike,
my first feedback is to propose a simpler data structure: an asset with a double key `string * address` 
```
asset tokens identified by id owner to big_map {
   id     : string;
   owner  : address;
   amount : nat = 0
}
```

Like that it is easy to change the value associated for example to string `"a"` and address `caller`:
```
tokens.add_update(("a", caller), { amount += 1 })
```

It is accessed this way:
```
const token_balance = tokens[("a", caller)] ? the.amount : 0
```

Here is the doc on options:
https://archetype-lang.org/docs/reference/types#option%3CT%3E
and more specifically on the ternary operator used above:
https://archetype-lang.org/docs/reference/expressions/controls#a--b--c

Here is a complete working example:
```
archetype a

asset tokens identified by  id owner {
   id     : string;
   owner  : address;
   amount : nat = 0
}

variable n : nat = 0

entry exec() {
  tokens.add_update(("a", caller), { amount += 1 });
  const token_balance = tokens[("a", caller)] ? the.amount : 0;
  n := token_balance
}
```

**Comment by evronm** [comment]
The problem with that structure is that you're storing the symbol in every record.  The relational dev in me rebels against it because it violates the normal forms, and the Eth dev in me rebels at how much storage, and hence gas, such a structure wastes.

Is there really no way to do what I'm trying to do?  Is it possible Ligo?  

I love Archetype conceptually, but I'm starting to run into the kinds of limitations that drove me here in the first place.  Is it possible I'm using it for my purposes prematurely?  Should I give you guys a another year or so to polish this thing up before trying something as complicated as a DAO with a multi-token vault and a 2 layer governance mechanism?

Also, is the slack active?  The link on the site doesn't work for me, and I feel kind of awkward posing these kinds of questions on github...

Thanks again.

**Comment by rognierbenoit** [comment]
indeed the string is duplicated, however there are several elements to consider:
* in your initial data structure, the top map is part of the contract storage, and as such it will be deserialised each time the contract is accessed (entry or view) with an associated cost; conversely the top big map is not part of the storage, hence it does not induce deserialisation cost at each operation
* the TZIP 12 norm for multiple tokens is using a top big map with a pair `nat * address` as key; the reason is linked to the above point
* the storage cost for a byte is 250 millionth of tez, hence for example, duplicating a 10 bytes string 10 000 times costs globally 2.5 tez (~3.5$), depending on the structure of your project it may be acceptable

As far as I know, storing big maps in basic containers is not common practice.

Now, it is possible to achieve what you want in archetype, for example:
```
 archetype tokens2

asset tokens {
   id      : string;
   ledger  : big_map<address, nat> = []
}
entry add(a : address, v : string, n : nat) {
  tokens.add_update(v, { });
  tokens[v].ledger.put(a, n)
}

view get_balance(a : address, v : string) : nat {
  return (tokens[v] ? (the.ledger[a] ? the : 0) : 0)
}
```

**Comment by evronm** [comment]
Aha!  Perfect!  Had I known I could use a big_map as an asset field type, I would have gone there immediately.  Thanks again!
