### ISSUE TITLE
provide `and` `or` `xor` for nat

### ISSUE THREAD

**Issue by rognierbenoit** [completium/archetype-lang#339]

**Comment by guillaumeduhamel** [comment]
Add:

- and: nat : nat -> nat
- and: int : nat -> nat
- or: nat -> nat -> nat

(`xor` already exists)

according to michelson ref:
https://tezos.gitlab.io/michelson-reference/#instr-AND
https://tezos.gitlab.io/michelson-reference/#instr-OR
https://tezos.gitlab.io/michelson-reference/#instr-XOR
