### ISSUE TITLE
Issue with self_address

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [completium/archetype-lang#362]
>Case: User is paying 1tz for minting item which will be revealed later. 

Code:
entry mint (tow : address, roy : list<part>) {
    require { fa2_r5: is_not_paused() }
    effect {
    transfer 1tz to self_address;
    ledger.add({ ltokenid = act_tid; lowner = tow });
    royalties.put({ rtokenid = act_tid; rvalue = roy });
    act_tid += 1
    }
}

Test: 

it('Mint tokens on FA2 as someone', async () => {
    try {
       await fa2_nft.mint(
        alice.get_address(),      
        [          
          new part(alice.get_address(), new Nat(1000)),
          new part(bob.get_address(), new Nat(500))
        ], {
        as: alice, amount: new Tez(1)
        }
        );
    } catch (error) {
      console.log("ERROR: ", error)
    }
    const act_tid = await fa2_nft.get_act_tid()
    assert(act_tid.equals(new Nat(1)))
  });`

Expected result: Test has passed

Error: ERROR:  { value: '"ENTRY_NOT_FOUND"' }

Maybe I've don't understand the documentation, but if I will replace the "self_address" with "owner" then everything is fine.

**Comment by rognierbenoit** [comment]
Hi Michal,
in order for a contract to receive tez, it needs to declare the following entry point:
```
entry default() {}
```
May I now question the rational behind the `transfer 1tz to self_address` ? it won't change the contract balance, and it will increase the execution cost.

**Comment by the-man-with-a-golden-mind** [comment]
Oh, thank you. Right. 
The use case is rather simple and taken from Eth NFT cases (which I am way more familiar).
So, owner is not minting NFT, users are minting them. The token_id is increased by 1 after each minting. Each time when user would like to mint he/she has to send for example 10tez into the smart contract. 
This is why I've thought that maybe I can do it by "transfer 1tez to self_address"

**Comment by the-man-with-a-golden-mind** [comment]
Oh, I see. I've put requirements that "transferred = 1tz" and not it is working. 
BTW can I even create the global token_id which will be increased by one after each minting?

**Comment by rognierbenoit** [comment]
sure, it's a common basic pattern to have a global incremented token_id; it seems very close to what you have with `act_tid` above.

**Comment by the-man-with-a-golden-mind** [comment]
Ok, I am closing the topic. I've another issues which I've found but they are not connected to self_address :) Thank you for clarification :)
