### ISSUE TITLE
How to convert nat to mutez?

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [completium/archetype-lang#363]
There is a function which is converting mutez_to_nat. It is awesome, because I can mak  some crazy calculations on royalties, calculate what I want. The issue is that at the end I am getting Nat. How I can convert it to mutez to know how much I have to send into the caller?

**Comment by rognierbenoit** [comment]
just multiply it by `1tz`
```
const a = 32 * 1tz // this is 32tz
```

It is likely that you can compute on tez type straightforwardly because rational multiplied by tez is still a tez; for example:
```
const royalties = 5% * transferred;
const price = transferred - royalties;
transfer price to owner;
transfer royalties to creator
```

**Comment by the-man-with-a-golden-mind** [comment]
I am keeping royalties as a Nat. So that "5%" trick would not work :(

**Comment by the-man-with-a-golden-mind** [comment]
Closing. Thank you for answer :)
