### ISSUE TITLE
Is Archetype is actively maintained?

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [completium/archetype-lang#364]
I've tried to check the possibility to verify my contract in ChatGTP and this is what I've got: 

"It is important to note that Archetype is no longer actively maintained, and LIGO has become the recommended language for Tezos smart contract development. Consider exploring LIGO or SmartPy for building FA2 contracts and marketplaces in Tezos."

**Comment by rognierbenoit** [comment]
Hi Michal, strange enough indeed. This is fake news from ChatGPT. Archetype is still maintained!

**Comment by rognierbenoit** [comment]
Was it from plain ChatGPT from openai or from an chatbot built on top of it ?

**Comment by the-man-with-a-golden-mind** [comment]
pure ChatGPT.

**Comment by the-man-with-a-golden-mind** [comment]
![Screenshot 2023-07-13 at 14 22 40](https://github.com/completium/archetype-lang/assets/5738576/949e9285-48b1-4364-857a-5a862195e5dd)
Now repeat it like a 1000 times and we can say that this issue has been solved? :D

**Comment by rognierbenoit** [comment]
which version is it ? 3.5 or 4 ?

**Comment by the-man-with-a-golden-mind** [comment]
3.5

**Comment by the-man-with-a-golden-mind** [comment]
Ask about example of NFT market place in Archetype or something like that. IMHO he knows that Archietype is active but in more complex scenarios he is returning wrong answer.

**Comment by rognierbenoit** [comment]
ok thanks for the feedback.

**Comment by the-man-with-a-golden-mind** [comment]
Closing because, there is no solution for that issue :D
