### ISSUE TITLE
What can be the key in big map?

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [completium/archetype-lang#366]
I can not find equivalent  of " map<[address,nat],offer>" (ligo) in archetype. 
Is is possible to create such key definitions? At the end Archietype would just hash it, right?

**Comment by rognierbenoit** [comment]
yes it is possible to have a tuple as key:
```
variable mymap : map<address * nat, offer> = []
```

then:
```
const o = mymap[(caller, 0)]
```

Usually we use [asset](https://archetype-lang.org/docs/asset) instead of map : it is the fusion of map and record.

**Comment by the-man-with-a-golden-mind** [comment]
ok, thx. I am closing that topic :)
